/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package si.bintegra.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CustomerService service. Represents a row in the &quot;FOO_CustomerService&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>si.bintegra.model.impl.CustomerServiceModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>si.bintegra.model.impl.CustomerServiceImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CustomerService
 * @generated
 */
@ProviderType
public interface CustomerServiceModel extends BaseModel<CustomerService> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a customer service model instance should use the {@link CustomerService} interface instead.
	 */

	/**
	 * Returns the primary key of this customer service.
	 *
	 * @return the primary key of this customer service
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this customer service.
	 *
	 * @param primaryKey the primary key of this customer service
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this customer service.
	 *
	 * @return the uuid of this customer service
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this customer service.
	 *
	 * @param uuid the uuid of this customer service
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the ID of this customer service.
	 *
	 * @return the ID of this customer service
	 */
	public long getId();

	/**
	 * Sets the ID of this customer service.
	 *
	 * @param id the ID of this customer service
	 */
	public void setId(long id);

	/**
	 * Returns the title of this customer service.
	 *
	 * @return the title of this customer service
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this customer service.
	 *
	 * @param title the title of this customer service
	 */
	public void setTitle(String title);

	/**
	 * Returns the price of this customer service.
	 *
	 * @return the price of this customer service
	 */
	public double getPrice();

	/**
	 * Sets the price of this customer service.
	 *
	 * @param price the price of this customer service
	 */
	public void setPrice(double price);

	@Override
	public CustomerService cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}