/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package si.bintegra.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the OfferOption service. Represents a row in the &quot;FOO_OfferOption&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>si.bintegra.model.impl.OfferOptionModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>si.bintegra.model.impl.OfferOptionImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see OfferOption
 * @generated
 */
@ProviderType
public interface OfferOptionModel extends BaseModel<OfferOption> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a offer option model instance should use the {@link OfferOption} interface instead.
	 */

	/**
	 * Returns the primary key of this offer option.
	 *
	 * @return the primary key of this offer option
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this offer option.
	 *
	 * @param primaryKey the primary key of this offer option
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this offer option.
	 *
	 * @return the uuid of this offer option
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this offer option.
	 *
	 * @param uuid the uuid of this offer option
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the ID of this offer option.
	 *
	 * @return the ID of this offer option
	 */
	public long getId();

	/**
	 * Sets the ID of this offer option.
	 *
	 * @param id the ID of this offer option
	 */
	public void setId(long id);

	/**
	 * Returns the offer ID of this offer option.
	 *
	 * @return the offer ID of this offer option
	 */
	public long getOfferId();

	/**
	 * Sets the offer ID of this offer option.
	 *
	 * @param offerId the offer ID of this offer option
	 */
	public void setOfferId(long offerId);

	/**
	 * Returns the full duration of this offer option.
	 *
	 * @return the full duration of this offer option
	 */
	public long getFullDuration();

	/**
	 * Sets the full duration of this offer option.
	 *
	 * @param fullDuration the full duration of this offer option
	 */
	public void setFullDuration(long fullDuration);

	/**
	 * Returns the discount duration of this offer option.
	 *
	 * @return the discount duration of this offer option
	 */
	public long getDiscountDuration();

	/**
	 * Sets the discount duration of this offer option.
	 *
	 * @param discountDuration the discount duration of this offer option
	 */
	public void setDiscountDuration(long discountDuration);

	/**
	 * Returns the discount price of this offer option.
	 *
	 * @return the discount price of this offer option
	 */
	public long getDiscountPrice();

	/**
	 * Sets the discount price of this offer option.
	 *
	 * @param discountPrice the discount price of this offer option
	 */
	public void setDiscountPrice(long discountPrice);

	/**
	 * Returns the full price of this offer option.
	 *
	 * @return the full price of this offer option
	 */
	public long getFullPrice();

	/**
	 * Sets the full price of this offer option.
	 *
	 * @param fullPrice the full price of this offer option
	 */
	public void setFullPrice(long fullPrice);

	/**
	 * Returns the active of this offer option.
	 *
	 * @return the active of this offer option
	 */
	public Boolean getActive();

	/**
	 * Sets the active of this offer option.
	 *
	 * @param active the active of this offer option
	 */
	public void setActive(Boolean active);

	@Override
	public OfferOption cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}