/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package si.bintegra.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

import si.bintegra.model.OfferOption;
import si.bintegra.model.OfferOptionModel;

/**
 * The base model implementation for the OfferOption service. Represents a row in the &quot;FOO_OfferOption&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>OfferOptionModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link OfferOptionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see OfferOptionImpl
 * @generated
 */
@JSON(strict = true)
public class OfferOptionModelImpl
	extends BaseModelImpl<OfferOption> implements OfferOptionModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a offer option model instance should use the <code>OfferOption</code> interface instead.
	 */
	public static final String TABLE_NAME = "FOO_OfferOption";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"id_", Types.BIGINT},
		{"offerId", Types.BIGINT}, {"fullDuration", Types.BIGINT},
		{"discountDuration", Types.BIGINT}, {"discountPrice", Types.BIGINT},
		{"fullPrice", Types.BIGINT}, {"active_", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("offerId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("fullDuration", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("discountDuration", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("discountPrice", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("fullPrice", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("active_", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table FOO_OfferOption (uuid_ VARCHAR(75) null,id_ LONG not null primary key,offerId LONG,fullDuration LONG,discountDuration LONG,discountPrice LONG,fullPrice LONG,active_ BOOLEAN)";

	public static final String TABLE_SQL_DROP = "drop table FOO_OfferOption";

	public static final String ORDER_BY_JPQL = " ORDER BY offerOption.id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY FOO_OfferOption.id_ ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public OfferOptionModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return OfferOption.class;
	}

	@Override
	public String getModelClassName() {
		return OfferOption.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<OfferOption, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<OfferOption, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<OfferOption, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((OfferOption)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<OfferOption, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<OfferOption, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(OfferOption)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<OfferOption, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<OfferOption, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<OfferOption, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<OfferOption, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<OfferOption, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<OfferOption, Object>>();
		Map<String, BiConsumer<OfferOption, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<OfferOption, ?>>();

		attributeGetterFunctions.put("uuid", OfferOption::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<OfferOption, String>)OfferOption::setUuid);
		attributeGetterFunctions.put("id", OfferOption::getId);
		attributeSetterBiConsumers.put(
			"id", (BiConsumer<OfferOption, Long>)OfferOption::setId);
		attributeGetterFunctions.put("offerId", OfferOption::getOfferId);
		attributeSetterBiConsumers.put(
			"offerId", (BiConsumer<OfferOption, Long>)OfferOption::setOfferId);
		attributeGetterFunctions.put(
			"fullDuration", OfferOption::getFullDuration);
		attributeSetterBiConsumers.put(
			"fullDuration",
			(BiConsumer<OfferOption, Long>)OfferOption::setFullDuration);
		attributeGetterFunctions.put(
			"discountDuration", OfferOption::getDiscountDuration);
		attributeSetterBiConsumers.put(
			"discountDuration",
			(BiConsumer<OfferOption, Long>)OfferOption::setDiscountDuration);
		attributeGetterFunctions.put(
			"discountPrice", OfferOption::getDiscountPrice);
		attributeSetterBiConsumers.put(
			"discountPrice",
			(BiConsumer<OfferOption, Long>)OfferOption::setDiscountPrice);
		attributeGetterFunctions.put("fullPrice", OfferOption::getFullPrice);
		attributeSetterBiConsumers.put(
			"fullPrice",
			(BiConsumer<OfferOption, Long>)OfferOption::setFullPrice);
		attributeGetterFunctions.put("active", OfferOption::getActive);
		attributeSetterBiConsumers.put(
			"active", (BiConsumer<OfferOption, Boolean>)OfferOption::setActive);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@JSON
	@Override
	public long getOfferId() {
		return _offerId;
	}

	@Override
	public void setOfferId(long offerId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_offerId = offerId;
	}

	@JSON
	@Override
	public long getFullDuration() {
		return _fullDuration;
	}

	@Override
	public void setFullDuration(long fullDuration) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fullDuration = fullDuration;
	}

	@JSON
	@Override
	public long getDiscountDuration() {
		return _discountDuration;
	}

	@Override
	public void setDiscountDuration(long discountDuration) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_discountDuration = discountDuration;
	}

	@JSON
	@Override
	public long getDiscountPrice() {
		return _discountPrice;
	}

	@Override
	public void setDiscountPrice(long discountPrice) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_discountPrice = discountPrice;
	}

	@JSON
	@Override
	public long getFullPrice() {
		return _fullPrice;
	}

	@Override
	public void setFullPrice(long fullPrice) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fullPrice = fullPrice;
	}

	@JSON
	@Override
	public Boolean getActive() {
		return _active;
	}

	@Override
	public void setActive(Boolean active) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_active = active;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, OfferOption.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public OfferOption toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, OfferOption>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		OfferOptionImpl offerOptionImpl = new OfferOptionImpl();

		offerOptionImpl.setUuid(getUuid());
		offerOptionImpl.setId(getId());
		offerOptionImpl.setOfferId(getOfferId());
		offerOptionImpl.setFullDuration(getFullDuration());
		offerOptionImpl.setDiscountDuration(getDiscountDuration());
		offerOptionImpl.setDiscountPrice(getDiscountPrice());
		offerOptionImpl.setFullPrice(getFullPrice());
		offerOptionImpl.setActive(getActive());

		offerOptionImpl.resetOriginalValues();

		return offerOptionImpl;
	}

	@Override
	public OfferOption cloneWithOriginalValues() {
		OfferOptionImpl offerOptionImpl = new OfferOptionImpl();

		offerOptionImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		offerOptionImpl.setId(this.<Long>getColumnOriginalValue("id_"));
		offerOptionImpl.setOfferId(
			this.<Long>getColumnOriginalValue("offerId"));
		offerOptionImpl.setFullDuration(
			this.<Long>getColumnOriginalValue("fullDuration"));
		offerOptionImpl.setDiscountDuration(
			this.<Long>getColumnOriginalValue("discountDuration"));
		offerOptionImpl.setDiscountPrice(
			this.<Long>getColumnOriginalValue("discountPrice"));
		offerOptionImpl.setFullPrice(
			this.<Long>getColumnOriginalValue("fullPrice"));
		offerOptionImpl.setActive(
			this.<Boolean>getColumnOriginalValue("active_"));

		return offerOptionImpl;
	}

	@Override
	public int compareTo(OfferOption offerOption) {
		int value = 0;

		if (getId() < offerOption.getId()) {
			value = -1;
		}
		else if (getId() > offerOption.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof OfferOption)) {
			return false;
		}

		OfferOption offerOption = (OfferOption)object;

		long primaryKey = offerOption.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<OfferOption> toCacheModel() {
		OfferOptionCacheModel offerOptionCacheModel =
			new OfferOptionCacheModel();

		offerOptionCacheModel.uuid = getUuid();

		String uuid = offerOptionCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			offerOptionCacheModel.uuid = null;
		}

		offerOptionCacheModel.id = getId();

		offerOptionCacheModel.offerId = getOfferId();

		offerOptionCacheModel.fullDuration = getFullDuration();

		offerOptionCacheModel.discountDuration = getDiscountDuration();

		offerOptionCacheModel.discountPrice = getDiscountPrice();

		offerOptionCacheModel.fullPrice = getFullPrice();

		Boolean active = getActive();

		if (active != null) {
			offerOptionCacheModel.active = active;
		}

		return offerOptionCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<OfferOption, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<OfferOption, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<OfferOption, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((OfferOption)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, OfferOption>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					OfferOption.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _id;
	private long _offerId;
	private long _fullDuration;
	private long _discountDuration;
	private long _discountPrice;
	private long _fullPrice;
	private Boolean _active;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<OfferOption, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((OfferOption)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("id_", _id);
		_columnOriginalValues.put("offerId", _offerId);
		_columnOriginalValues.put("fullDuration", _fullDuration);
		_columnOriginalValues.put("discountDuration", _discountDuration);
		_columnOriginalValues.put("discountPrice", _discountPrice);
		_columnOriginalValues.put("fullPrice", _fullPrice);
		_columnOriginalValues.put("active_", _active);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put("id_", "id");
		attributeNames.put("active_", "active");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("id_", 2L);

		columnBitmasks.put("offerId", 4L);

		columnBitmasks.put("fullDuration", 8L);

		columnBitmasks.put("discountDuration", 16L);

		columnBitmasks.put("discountPrice", 32L);

		columnBitmasks.put("fullPrice", 64L);

		columnBitmasks.put("active_", 128L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private OfferOption _escapedModel;

}